#!/bin/bash
 rm abelcomp.cpp
 rm abelw2comp.cpp
 rm compareCxsec.cpp
 rm cxAndratios.cpp
 rm cxAndratios2.cpp
 rm diffCuts
 rm extractCS.cpp.save
 rm figure1.cpp
 rm figure1_318.cpp
 rm figure2.cpp
 rm figure2_318.cpp
 rm figure3.cpp
 rm figure318.cpp
 rm figure4.cpp
 rm hmsCxAndRatios.cpp
 rm jam21.cpp
 rm multipad.cpp
 rm nim.cpp
 rm percDiff.cpp
 rm plor_cx_shmsHms.cpp
 rm plotRatios.cpp
 rm plot_cxAr.cpp
 rm plot_cxOnly.cpp
 rm plot_cxShmsHms.cpp
 rm plot_cx_3pad.cpp
 rm plot_cx_beforeHisto.cpp
 rm plot_cx_f1.cpp
 rm plot_cx_f3.cpp
 rm plot_cx_hms.cpp
 rm plot_cx_models.cpp
 rm plot_cx_norm_cj.cpp
 rm plot_cx_raffaella.cpp
 rm plot_cx_shmsHms.cpp
 rm plot_dataMc.cpp
 rm plot_nim.cpp
 rm plot_ratioOnly.cpp
 rm plotjam21.cpp
 rm ratios4paper.cpp
 rm ratiosPlot.cpp
 rm runAll.sh
 rm runDeut.sh
 rm runw2Vdelta.sh
 rm runw2vmodel.sh
 rm shmsHms.cpp
 rm shmsVhms.cpp
 rm stupid.cpp
 rm w2Vdelta.cpp
 rm w2VdiffModels.cpp
