#!/Bin/bash
#SHMS Carbon
root -b -q 'mcWt.cpp("c","21","3p3","hms")'
root -b -q 'mcWt.cpp("c","21","4p0","hms")'
root -b -q 'mcWt.cpp("c","21","5p1","hms")'
root -b -q 'mcWt.cpp("c","21","5p7","hms")'
root -b -q 'mcWt.cpp("c","21","2p7","shms")'
root -b -q 'mcWt.cpp("c","21","3p3","shms")'
root -b -q 'mcWt.cpp("c","21","4p0","shms")'
root -b -q 'mcWt.cpp("c","21","5p1","shms")'
root -b -q 'mcWt.cpp("c","25","4p4","shms")'
root -b -q 'mcWt.cpp("c","25","3p5","shms")'
root -b -q 'mcWt.cpp("c","25","3p0","shms")'
root -b -q 'mcWt.cpp("c","25","2p5","shms")'
root -b -q 'mcWt.cpp("c","29","3p7","shms")'
root -b -q 'mcWt.cpp("c","29","3p0","shms")'
root -b -q 'mcWt.cpp("c","29","2p4","shms")'
root -b -q 'mcWt.cpp("c","29","2p0","shms")'
root -b -q 'mcWt.cpp("c","33","3p2","shms")'
root -b -q 'mcWt.cpp("c","33","2p6","shms")'
root -b -q 'mcWt.cpp("c","33","2p1","shms")'
root -b -q 'mcWt.cpp("c","33","1p7","shms")'
root -b -q 'mcWt.cpp("c","39","2p5","shms")'
root -b -q 'mcWt.cpp("c","39","2p0","shms")'
root -b -q 'mcWt.cpp("c","39","1p6","shms")'
root -b -q 'mcWt.cpp("c","39","1p3","shms")'
